/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Student;

import DataType.Classes.Classes;
import DataType.Classes.ClassesDaoImpl;
import java.awt.Dimension;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author kumar
 */
public class StudentAccount extends javax.swing.JInternalFrame {

    /**
     * Creates new form StudentAccount
     */
    public StudentAccount() {
        initComponents();
    }

    public StudentAccount(Dimension size) {
         initComponents();
        setBounds(0,0,size.width-10, size.height-10);
      setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        ID1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        STUDCLASS = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        ID2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 255, 102));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setAutoscrolls(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Reg. ID :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 20, 55, 17);

        ID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(ID);
        ID.setBounds(87, 20, 160, 23);

        ID1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(ID1);
        ID1.setBounds(310, 60, 150, 23);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Name :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(260, 60, 44, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Class :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(260, 20, 39, 17);
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(310, 20, 154, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Sec. :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 60, 35, 17);

        STUDCLASS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C" }));
        getContentPane().add(STUDCLASS);
        STUDCLASS.setBounds(90, 60, 154, 20);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("GO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(950, 70, 90, 20);

        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 97, 240, 300);

        jPanel1.setLayout(null);

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Fee Type ", "Fee"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(10, 11, 739, 164);

        jLabel5.setBackground(new java.awt.Color(255, 204, 204));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Total Dues :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(100, 210, 90, 17);

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 523, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 281, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(226, 193, 523, 281);

        jLabel6.setBackground(new java.awt.Color(255, 204, 204));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Paid Amount :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 280, 110, 17);

        jLabel7.setBackground(new java.awt.Color(255, 204, 204));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Discount :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 240, 74, 17);

        jLabel8.setBackground(new java.awt.Color(255, 204, 204));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Total Dues :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 210, 74, 17);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField1.setText("0");
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(100, 240, 100, 23);

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField2.setText("0");
        jPanel1.add(jTextField2);
        jTextField2.setBounds(100, 280, 100, 23);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Paid");
        jPanel1.add(jButton2);
        jButton2.setBounds(20, 340, 100, 30);

        jTabbedPane1.addTab("Dues", jPanel1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("History", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 779, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 479, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Panding", jPanel4);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(265, 97, 784, 507);

        ID2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(ID2);
        ID2.setBounds(760, 70, 170, 23);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Father Name :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(660, 70, 90, 17);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("place:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(710, 30, 36, 17);
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(754, 30, 290, 20);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("GO");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(480, 20, 70, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        System.out.print("Student Acound loded");
    }//GEN-LAST:event_formInternalFrameActivated
    List classList = null;
    Classes cls[] = null;
    List AddList = null;
    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        ClassesDaoImpl cdi = new ClassesDaoImpl();
        cls = cdi.selectClasses();
        for(int i = 0 ; i < cls.length; i++){
            if(cls[i] == null)
                System.out.println("null ");
            else
                jComboBox1.addItem(cls[i].getName());
        }
        
//        
        StudentACImpl saci = new StudentACImpl();
        AddList = saci.getUniqueAddressList();
        for(int i = 0 ; i < AddList.size(); i++){
            jComboBox2.addItem((String)AddList.get(i));
        }
        
        
    }//GEN-LAST:event_formInternalFrameOpened
    List studList = null; //student list search 
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String fname = ID2.getText();
        String address = jComboBox2.getSelectedItem().toString();
        
        DefaultListModel<String> dlmPer = new DefaultListModel<String>();
        StudentACImpl sacd = new StudentACImpl();

        studList = sacd.getStudentListByFatherName(fname,address);
        for(int i = 0 ; i < studList.size(); i++){
//                System.out.print( studList.get(i).toString());
            Student Data = (Student) studList.get(i);
            dlmPer.addElement(Data.getName());
        }
        jList1.setModel(dlmPer);
    }//GEN-LAST:event_jButton1ActionPerformed
    FeeTypeClass  ftc = null;
    int TotalFee = 0 ;
    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        int index = jList1.locationToIndex(evt.getPoint());
        Student selectedStud = (Student) studList.get(index);
        System.out.println("index: "+index+" id :"+selectedStud.getRegID()+" name:"+selectedStud.getName());
        StudentACImpl sacd = new StudentACImpl();
        ftc = sacd.getAllFee(selectedStud.getRegID());
        
        int OldFee = ftc.getOldFee();
        int TransFee = ftc.getTransFee();
        int supplyFee = ftc.getsupplyFee();
        int tutionFee = ftc.gettutionFee();
        int examFee = ftc.getexamFee();
        int compFee = ftc.getcompFee();
        int annFee = ftc.getannualFee();
        Object[] rowOld = {"Old fee", OldFee};
        Object[] rowTrans = {"Tranport fee", TransFee};
        Object[] rowSupply = {"Supply fee", supplyFee};
        Object[] rowTution = {"Tution fee", tutionFee};
        Object[] rowExam = {"Exam fee", examFee};
        Object[] rowComp = {"Computer fee", compFee};
        Object[] rowAnual = {"Annual fee", annFee};

        DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
        try{
            int rowCount = tm.getRowCount();
            //Remove rows one by one from the end of the table
            for (int i = rowCount - 1; i >= 0; i--) {
                tm.removeRow(i);
            }

        }catch(Exception e){
            System.out.println("reving failed");
        }
        
        tm.addRow(rowOld); 
        tm.addRow(rowTrans);
        tm.addRow(rowSupply);
        tm.addRow(rowTution);
        tm.addRow(rowExam);
        tm.addRow(rowComp);
        tm.addRow(rowAnual);
        TotalFee = OldFee+TransFee+supplyFee+tutionFee+examFee+compFee+annFee;
//      showing total fee
        jLabel5.setText(String.valueOf(TotalFee));

    }//GEN-LAST:event_jList1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String RegNo = ID.getText();
        String StudName = ID1.getText();
        String StudSec = STUDCLASS.getSelectedItem().toString();
        
        String studstudclass = jComboBox1.getSelectedItem().toString();
        
        int classID = 0 ;
        for(int i =0 ; i < cls.length ; i ++){
            if(cls[i] != null){
                if(cls[i].getName().equals(studstudclass)){
                    System.out.println("foundi ");
                    classID = cls[i].getId();
                }
            }
        }
        
        
        StudentACImpl sacd = new StudentACImpl();
        
        if(RegNo.trim().length() > 0){
            DefaultListModel<String> dlm = new DefaultListModel<String>();
            studList = sacd.getStudentListByRegno(RegNo);
            for(int i = 0 ; i < studList.size(); i++){
//                System.out.print( studList.get(i).toString());
                Student Data = (Student) studList.get(i);
                dlm.addElement(Data.getName());
            }
            jList1.setModel(dlm);
        }else{
            DefaultListModel<String> dlm = new DefaultListModel<String>();
            System.out.println("studname:"+StudName+" claddid:"+(classID)+" studsec :"+StudSec);
            studList = sacd.getStudentListByName(StudName,String.valueOf(classID),StudSec);
            for(int i = 0 ; i < studList.size(); i++){
//                System.out.print( studList.get(i).toString());
                Student Data = (Student) studList.get(i);
                dlm.addElement(Data.getName());
            }
            jList1.setModel(dlm);
        }
        JOptionPane.showMessageDialog(null, studList.size() + " Record Found ", "InfoBox: Search Result", JOptionPane.INFORMATION_MESSAGE); 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        try{
            jTextField2.setText(String.valueOf(Integer.valueOf(TotalFee)-Integer.valueOf(jTextField1.getText())));
        }catch(Exception e){
            System.out.println("calcultion value");
        }
    }//GEN-LAST:event_jTextField1FocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID;
    private javax.swing.JTextField ID1;
    private javax.swing.JTextField ID2;
    private javax.swing.JComboBox<String> STUDCLASS;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
