/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DataType.Employ;

import java.awt.Dimension;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author kumar
 */
public class EmployeEntry extends javax.swing.JInternalFrame {

    /**
     * Creates new form EmployeEntry
     */
    public EmployeEntry() {
        initComponents();
    }

    public EmployeEntry(Dimension size) {
        initComponents();
        setBounds(0,0,size.width-10, size.height-10);
      setVisible(true);
      clearField();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gender = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        castTxt = new javax.swing.JTextField();
        father = new javax.swing.JTextField();
        male = new javax.swing.JRadioButton();
        name = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        dob = new com.toedter.calendar.JDateChooser();
        jLabel37 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fmale = new javax.swing.JRadioButton();
        ph2 = new javax.swing.JTextField();
        mother = new javax.swing.JTextField();
        religion = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        empSubmit = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        ph3 = new javax.swing.JTextField();
        type = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setAutoscrolls(true);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane1.setAutoscrolls(true);

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("ID :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 11, 23, 17);

        id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        id.setText("-----------");
        jPanel1.add(id);
        id.setBounds(51, 11, 179, 17);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Mobile No. 2 : ");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(410, 360, 87, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Father :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(62, 104, 48, 17);

        castTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(castTxt);
        castTxt.setBounds(130, 310, 251, 23);

        father.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(father);
        father.setBounds(128, 101, 251, 23);

        gender.add(male);
        male.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        male.setSelected(true);
        male.setText("Male");
        jPanel1.add(male);
        male.setBounds(510, 70, 51, 25);

        name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(name);
        name.setBounds(128, 60, 251, 23);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Caste :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(60, 310, 43, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Name :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(66, 63, 44, 17);

        email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(email);
        email.setBounds(130, 400, 251, 23);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("DOB :");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(449, 114, 37, 17);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Email :");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(60, 400, 83, 17);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Gender :");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(427, 70, 60, 17);

        dob.setAutoscrolls(true);
        dob.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(dob);
        dob.setBounds(504, 111, 200, 30);

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel37.setText("Religion :");
        jPanel1.add(jLabel37);
        jLabel37.setBounds(423, 310, 70, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Mother :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(62, 145, 52, 17);

        gender.add(fmale);
        fmale.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fmale.setText("Female");
        jPanel1.add(fmale);
        fmale.setBounds(580, 70, 67, 25);

        ph2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(ph2);
        ph2.setBounds(510, 360, 251, 23);

        mother.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mother.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motherActionPerformed(evt);
            }
        });
        jPanel1.add(mother);
        mother.setBounds(128, 142, 251, 23);

        religion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(religion);
        religion.setBounds(510, 310, 251, 23);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Address :");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(60, 180, 57, 17);

        address.setColumns(20);
        address.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        address.setLineWrap(true);
        address.setRows(5);
        address.setWrapStyleWord(true);
        jScrollPane2.setViewportView(address);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(120, 180, 442, 119);

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(320, 440, 190, 30);

        empSubmit.setBackground(new java.awt.Color(51, 51, 255));
        empSubmit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        empSubmit.setText("Submit");
        empSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                empSubmitMouseClicked(evt);
            }
        });
        jPanel1.add(empSubmit);
        empSubmit.setBounds(70, 440, 210, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Mobile No. 1 :");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(25, 363, 120, 17);

        ph3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(ph3);
        ph3.setBounds(130, 360, 251, 23);

        type.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Teacher", "Non-Teaching", "Principle", "Other" }));
        jPanel1.add(type);
        type.setBounds(250, 20, 196, 23);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Select Type :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(160, 20, 80, 17);

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //my code
    private void clearField(){
        this.address.setText("");
        this.castTxt.setText("");
        this.email.setText("");
        this.father.setText("");
        this.mother.setText("");
        this.name.setText("");
        this.ph2.setText("");
        this.ph3.setText("");
        this.religion.setText("");
         DateFormat df = new SimpleDateFormat("d MMM, yyyy");
      this.dob.setDate(new Date());
       
    }
    private void motherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_motherActionPerformed

    private void empSubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empSubmitMouseClicked
         if("Submit" == this.empSubmit.getText()){
             System.out.printf("Submit click");
            Employ obj = new Employ();
            obj.setName(this.name.getText());
            obj.setAddress(this.address.getText());
            obj.setEmail(this.email.getText());
            obj.setPh1(this.ph2.getText());
            obj.setPh2(this.ph3.getText());
            obj.setCast(this.castTxt.getText());
            obj.setReligion(this.religion.getText());
            obj.setType(this.type.getItemAt(this.type.getSelectedIndex()));
            obj.setReligion(this.religion.getText());
            obj.setFather(this.father.getText());
            obj.setMother(this.mother.getText());
            obj.setDob(this.dob.getDate());
            obj.setGender(this.male.isSelected()? 1:this.fmale.isSelected()? 2:0);
            int i = new EmployDaoImpl().insertEmploy(obj);
            if(i!=0){
                System.out.print("Data inserted Employ ID :"+i);
                JOptionPane.showMessageDialog(this,"Data Save...Employ ID :"+i);
                clearField();

            }
            else{
                System.out.print("error during save");
                JOptionPane.showMessageDialog(this,"Error during save Retry..");
            }
        }
        else if("Update" == this.empSubmit.getText()){
            System.out.printf("\n--->Under update");
          /**  Classes clas = new Classes();
            clas.setName(className.getText());
            clas.setTutionFee(Integer.parseInt(tutionFee.getText()));
            clas.setComputer(Integer.parseInt(ComputerFee.getText()));
            clas.setId(Integer.parseInt(cID.getText()));
            int i = new ClassesDaoImpl().updateClasses(clas);

            if(i!=0){
                System.out.print("Data inserted");
                JOptionPane.showMessageDialog(this,"Data Save...");
                save.setText("Save");
                clearField();
            }
            else{
                System.out.print("error during save");
                JOptionPane.showMessageDialog(this,"Error during save Retry..");
            }*/
        }
    }//GEN-LAST:event_empSubmitMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        clearField();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea address;
    private javax.swing.JTextField castTxt;
    private com.toedter.calendar.JDateChooser dob;
    private javax.swing.JTextField email;
    private javax.swing.JButton empSubmit;
    private javax.swing.JTextField father;
    private javax.swing.JRadioButton fmale;
    private javax.swing.ButtonGroup gender;
    private javax.swing.JLabel id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField mother;
    private javax.swing.JTextField name;
    private javax.swing.JTextField ph2;
    private javax.swing.JTextField ph3;
    private javax.swing.JTextField religion;
    private javax.swing.JComboBox<String> type;
    // End of variables declaration//GEN-END:variables
}
