/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package product.transaction;

import DataType.Session.Session;
import product.*;
import java.awt.Dimension;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kumar
 */
public class TransctionUI extends javax.swing.JInternalFrame {
   
    private TransactionDaoImpl tdi = new TransactionDaoImpl();
    Stock[] data;
    Transaction[] trns = new Transaction[20];
    Cart crt = new Cart();
    Session[] ses;
    int sl =0;
    private String session;
    private int sid;
    private int admid;
    private int regNo;
    private int crt_id;
    /**
     * Creates new form StudentAdmissionStage2
     */
    public TransctionUI() {
        initComponents();
        setData();
    }
    
     public TransctionUI(Dimension size) {
        initComponents();
        this.setData();
        setBounds(0,0,size.width-10, size.height-10);
        setVisible(true);
        for(int i = 0; i<19 ;i++){
            trns[i] = new Transaction();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        PList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        pname = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        stockId = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        items = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ritems = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        rate = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        size = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        VQuantity = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        sSearch = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        stClass = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        stRoll = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        stSec = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        stSession = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        admissionNo = new javax.swing.JTextField();
        sessionList = new javax.swing.JComboBox<>();
        SearchAS = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        TPValue = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 255, 102));
        setClosable(true);
        setForeground(new java.awt.Color(153, 51, 0));
        setMaximizable(true);
        setResizable(true);
        setAutoscrolls(true);
        getContentPane().setLayout(null);

        PList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                PListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(PList);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 220, 200, 400);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Product :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(340, 220, 60, 30);

        addButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addButton.setText("Submit");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addButton);
        addButton.setBounds(570, 550, 110, 30);

        pname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pname.setForeground(new java.awt.Color(204, 51, 0));
        pname.setText("....");
        getContentPane().add(pname);
        pname.setBounds(420, 220, 110, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Stock Id :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(340, 260, 80, 20);

        stockId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        stockId.setForeground(new java.awt.Color(204, 51, 0));
        stockId.setText("....");
        getContentPane().add(stockId);
        stockId.setBounds(420, 260, 100, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Items :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(360, 300, 50, 20);

        items.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        items.setForeground(new java.awt.Color(204, 51, 0));
        items.setText("....");
        getContentPane().add(items);
        items.setBounds(420, 300, 110, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Remains Items :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(300, 330, 100, 20);

        ritems.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ritems.setForeground(new java.awt.Color(204, 51, 0));
        ritems.setText("....");
        getContentPane().add(ritems);
        ritems.setBounds(420, 330, 120, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Rate :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(370, 410, 43, 17);

        rate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rate.setForeground(new java.awt.Color(204, 51, 0));
        rate.setText("....");
        getContentPane().add(rate);
        rate.setBounds(420, 410, 120, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Size :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(360, 370, 40, 14);

        size.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        size.setForeground(new java.awt.Color(153, 51, 0));
        size.setText("....");
        getContentPane().add(size);
        size.setBounds(420, 370, 110, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Quantity :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(320, 480, 70, 17);

        VQuantity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        VQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                VQuantityKeyPressed(evt);
            }
        });
        getContentPane().add(VQuantity);
        VQuantity.setBounds(400, 470, 120, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(410, 550, 100, 30);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(sSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 140, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 80, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Enter Registration No.");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Class :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, -1, 22));

        stClass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        stClass.setForeground(new java.awt.Color(153, 51, 0));
        stClass.setText("....");
        jPanel1.add(stClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 130, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Roll  :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 40, 30));

        stRoll.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        stRoll.setForeground(new java.awt.Color(153, 51, 0));
        stRoll.setText("....");
        jPanel1.add(stRoll, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 100, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Sec   :");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 100, -1, 30));

        stSec.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        stSec.setForeground(new java.awt.Color(153, 51, 0));
        stSec.setText("....");
        jPanel1.add(stSec, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 100, 130, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Session :");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 140, 70, 20));

        stSession.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        stSession.setForeground(new java.awt.Color(153, 51, 0));
        stSession.setText("....");
        jPanel1.add(stSession, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 130, 140, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 102, 102));
        jLabel8.setText("OR");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Admission No: ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, -1, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Session : ");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 30, -1, 20));

        admissionNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(admissionNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 130, 30));

        sessionList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sessionList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(sessionList, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 30, 120, 30));

        SearchAS.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SearchAS.setText("Search");
        SearchAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchASActionPerformed(evt);
            }
        });
        jPanel1.add(SearchAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 33, 100, 30));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(50, 20, 1190, 180);

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S/L No.", "P Name", "Quantity", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(740, 220, 500, 290);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Add To Cart");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(570, 470, 110, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Total Price :");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(550, 410, 80, 17);

        TPValue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TPValue.setForeground(new java.awt.Color(153, 51, 0));
        TPValue.setText("0");
        getContentPane().add(TPValue);
        TPValue.setBounds(640, 410, 80, 17);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_PListValueChanged
        String pname1 = PList.getSelectedValue();
        pname.setText(pname1);
        int i = PList.getSelectedIndex();
        //trns.setProductID(data[i].getPid());
        rate.setText(String.valueOf(data[i].getRate()));
        stockId.setText(String.valueOf(data[i].getId()));
        items.setText(String.valueOf(data[i].getQuantity()));
        ritems.setText(String.valueOf(data[i].getRQuantity()));
        size.setText(data[i].getSize());
    }//GEN-LAST:event_PListValueChanged

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
             
                // String VP =  VPrice.getText();
                int ind = PList.getSelectedIndex();
            
                for(int in =0;in<sl;in++)
                {
                   System.out.println(trns[in].getProductID());
                   System.out.println("sl :"+sl);
                   tdi.insertTransaction(trns[in]);
                }
              
                for(Stock stk:data){
                    try{
                        if(stk.isCheck() == true){
                            System.out.println(stk.getPName());
                             tdi.UpdateStock(stk);
                        }
                    }
                    catch(Exception e){
                        
                    }
                }
               
               double total = Double.parseDouble(TPValue.getText());
               double dues = total ;
               crt.setDues(dues);
               crt.setPrice(total);
               crt.setAdmissionId(admid);
               crt.setSession(sid);
               
               int f = tdi.insertCart(crt);
               if(f > 0)
               {
                   JOptionPane.showMessageDialog(null, "Updated Successfully", "", JOptionPane.INFORMATION_MESSAGE);
                   this.reset();
                   sl= 0 ;
               }
               else
               {
                   JOptionPane.showMessageDialog(null, "Somethng is wrong", "", JOptionPane.INFORMATION_MESSAGE);
               }
             
             //dlm.addElement(value); 
    }//GEN-LAST:event_addButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String value = sSearch.getText();
        crt_id = tdi.selectCartId();
        crt_id += 1;
             System.out.print(value);
             if(value != ""){
                 String[] str = tdi.selectStudent(value);
                 stClass.setText(str[6]);
                 stRoll.setText(str[3]);
                 stSession.setText(str[7]);
                 stSec.setText(str[4]);
                 admid = Integer.parseInt(str[0]);
                 session = str[7];
                 sid = Integer.parseInt(str[5]);
                 regNo = Integer.parseInt(value);
             }
             else{
                 JOptionPane.showMessageDialog(null, "Input Box is Empty.", "", JOptionPane.INFORMATION_MESSAGE);
                 pname.setFocusable(true);
             }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void VQuantityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VQuantityKeyPressed
         
    }//GEN-LAST:event_VQuantityKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.reset();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        String vq = VQuantity.getText();
        int qnt = 0;
        try{
            qnt = Integer.parseInt(vq);
        }
        catch(Exception e){
            
        }
        int ind = PList.getSelectedIndex();
        double Price = qnt * data[ind].getRate();
        trns[sl].setAdmissionID(admid);
        trns[sl].setRegNo(regNo);
        trns[sl].setSid(sid);
        trns[sl].setProductID(data[ind].getPid());
        trns[sl].setQuntity(qnt);
        trns[sl].setPrice(Price);
        trns[sl].setCart_id(crt_id);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{++sl,data[ind].getPName(),String.valueOf(qnt),String.valueOf(Price)});
        
        try{
            double total = Double.parseDouble(TPValue.getText());
            TPValue.setText(String.valueOf(total+Price));
        }
        catch(Exception ex){
        
        }
        finally{
            //TPValue.setText(String.valueOf(Price));
        }
        int rq = data[ind].getRQuantity();
        if(qnt > rq){
            JOptionPane.showMessageDialog(null, (qnt - rq)+"Items Pending", "", JOptionPane.INFORMATION_MESSAGE);
            trns[sl-1].setStatus(0);
            crt.setStatus(0);
            data[ind].setRQuantity(0);
            ritems.setText("0");
            data[ind].setStatus(0);
            tdi.UpdateStockStatus(data[ind]);
        }
        else{
            trns[sl-1].setStatus(1);
            data[ind].setRQuantity(rq-qnt);
            ritems.setText(String.valueOf(rq-qnt));
           // data[ind].setQuantity(rq-qnt);
        }
        data[ind].setCheck(true);
        VQuantity.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void SearchASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchASActionPerformed
        String value = admissionNo.getText();
        crt_id = tdi.selectCartId();
        crt_id += 1;
        System.out.print(value);
        if(value != ""){
            int ind = this.sessionList.getSelectedIndex();
            String[] str = tdi.selectStudent1(Integer.parseInt(value),ses[ind].getId());
            stClass.setText(str[6]);
            stRoll.setText(str[3]);
            stSession.setText(str[7]);
            stSec.setText(str[4]);
            admid = Integer.parseInt(str[0]);
            session = str[7];
            sid = Integer.parseInt(str[5]);
            regNo = Integer.parseInt(value);
        }
        else{
            JOptionPane.showMessageDialog(null, "Input Box is Empty.", "", JOptionPane.INFORMATION_MESSAGE);
            pname.setFocusable(true);
        }
    }//GEN-LAST:event_SearchASActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> PList;
    private javax.swing.JButton SearchAS;
    private javax.swing.JLabel TPValue;
    private javax.swing.JTextField VQuantity;
    private javax.swing.JButton addButton;
    private javax.swing.JTextField admissionNo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel items;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel pname;
    private javax.swing.JLabel rate;
    private javax.swing.JLabel ritems;
    private javax.swing.JTextField sSearch;
    private javax.swing.JComboBox<String> sessionList;
    private javax.swing.JLabel size;
    private javax.swing.JLabel stClass;
    private javax.swing.JLabel stRoll;
    private javax.swing.JLabel stSec;
    private javax.swing.JLabel stSession;
    private javax.swing.JLabel stockId;
    // End of variables declaration//GEN-END:variables

    @SuppressWarnings("unchecked")
    private void setData() {
        System.out.println("Mehod Called");
        data = tdi.selectStock();
        
        
        DefaultListModel<String> model = new DefaultListModel<>();
        this.PList.setModel(model);
        
        
        
        
        try{
            ses =  tdi.selectSession();
            DefaultComboBoxModel dcm = new DefaultComboBoxModel<>();
            this.sessionList.setModel(dcm);
            for (Session ses1 : ses) {
                System.out.println(ses1.getName());
                dcm.addElement(ses1.getName());
            }    
        }catch(Exception ex){
            System.out.print(ex);
        }
        
        try{
            for (Stock data1 : data) {
                System.out.println(data1.getPName());
                model.addElement(data1.getPName()+"(" +data1.getSize() + ")");
            }    
        }catch(Exception ex){
            System.out.print(ex);
        }
    }

    private void reset() {
        VQuantity.setText("");
        DefaultTableModel model = (DefaultTableModel) this.jTable1.getModel();
        model.setRowCount(0);
        TPValue.setText("0");
        
        for (Stock stk:data) {
            stk.setCheck(false);
        }
        

//        int rows = jTable1.getRowCount();
//        for(int i=0;i<rows;i++){
//          model.removeRow(i);
//        }
    }
}
