/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package product.transaction;

import DataType.Session.Session;
import product.*;
import java.awt.Dimension;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kumar
 */
public class TransctionReport extends javax.swing.JInternalFrame {
   
    private TransactionDaoImpl tdi = new TransactionDaoImpl();
    Stock[] data;
    Transaction[] trns = new Transaction[20];
    Cart[] crt;
    Session[] ses;
    int sl =0;
    private String session;
    private int sid;
    private int admid;
    private int regNo;
    /**
     * Creates new form StudentAdmissionStage2
     */
    public TransctionReport() {
        initComponents();
        setData();
    }
    
     public TransctionReport(Dimension size) {
        initComponents();
        this.setData();
        setBounds(0,0,size.width-10, size.height-10);
        setVisible(true);
        for(int i = 0; i<19 ;i++){
            trns[i] = new Transaction();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        PList = new javax.swing.JList<>();
        addButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        stClass = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        stRoll = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        stSec = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        stSession = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        admissionNo = new javax.swing.JTextField();
        sessionList = new javax.swing.JComboBox<>();
        SearchAS = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(102, 255, 102));
        setClosable(true);
        setForeground(new java.awt.Color(153, 51, 0));
        setMaximizable(true);
        setResizable(true);
        setAutoscrolls(true);
        getContentPane().setLayout(null);

        PList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                PListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(PList);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 200, 200, 260);

        addButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addButton.setText("Submit");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addButton);
        addButton.setBounds(430, 340, 110, 30);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Class :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, -1, 22));

        stClass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        stClass.setForeground(new java.awt.Color(153, 51, 0));
        stClass.setText("....");
        jPanel1.add(stClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, 130, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Roll  :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 40, 30));

        stRoll.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        stRoll.setForeground(new java.awt.Color(153, 51, 0));
        stRoll.setText("....");
        jPanel1.add(stRoll, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, 100, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Sec   :");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 30, -1, 30));

        stSec.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        stSec.setForeground(new java.awt.Color(153, 51, 0));
        stSec.setText("....");
        jPanel1.add(stSec, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 30, 130, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Session :");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 70, 70, 20));

        stSession.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        stSession.setForeground(new java.awt.Color(153, 51, 0));
        stSession.setText("....");
        jPanel1.add(stSession, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 60, 140, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Admission No: ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Session : ");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, 20));

        admissionNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(admissionNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 130, 30));

        sessionList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sessionList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(sessionList, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 130, 30));

        SearchAS.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SearchAS.setText("Search");
        SearchAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchASActionPerformed(evt);
            }
        });
        jPanel1.add(SearchAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 100, 30));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(50, 20, 1190, 130);

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S/L No.", "P Name", "Quantity", "Price", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setHeaderValue("S/L No.");
            jTable1.getColumnModel().getColumn(1).setHeaderValue("P Name");
            jTable1.getColumnModel().getColumn(2).setHeaderValue("Quantity");
            jTable1.getColumnModel().getColumn(3).setHeaderValue("Price");
            jTable1.getColumnModel().getColumn(4).setHeaderValue("Status");
        }

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(670, 180, 570, 290);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Cart List");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(50, 170, 50, 15);

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox1.setText("Delivered ");
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(430, 270, 110, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_PListValueChanged
        String pname1 = PList.getSelectedValue();
        int i = PList.getSelectedIndex();
        sl = 0;
        trns = tdi.selectTransaction(crt[i].getcId());
        if(trns.length > 0){
            //trns = tdi.
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            for(Transaction trn:trns){
                model.addRow(new Object[]{++sl,trn.getName(),trn.getQuntity(),trn.getPrice(),trn.getStatus()});
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "No Record Found.", "", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_PListValueChanged

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
             
                 
    }//GEN-LAST:event_addButtonActionPerformed

    private void SearchASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchASActionPerformed
        String value = admissionNo.getText();
        System.out.print(value);
        if(value != ""){
            int ind = this.sessionList.getSelectedIndex();
            crt = tdi.selectCart();   
            DefaultListModel<String> model = new DefaultListModel<>();
            this.PList.setModel(model);
            
            String[] str = tdi.selectStudent1(Integer.parseInt(value),ses[ind].getId());
            if(str.length > 0){
                stClass.setText(str[6]);
                stRoll.setText(str[3]);
                stSession.setText(str[7]);
                stSec.setText(str[4]);
                admid = Integer.parseInt(str[0]);
                session = str[7];
                sid = Integer.parseInt(str[5]);
                regNo = Integer.parseInt(value);
                if(crt.length > 0){
                    try{
                        for (Cart data1 : crt) {
                            System.out.println(data1.getcId());
                            model.addElement(data1.getcId()+" (" +data1.getCreated_at() + ")");
                        }    
                    }catch(Exception ex){
                        System.out.print(ex);
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null, "No Cart Found.", "", JOptionPane.INFORMATION_MESSAGE);
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "No Record Found.", "", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Input Box is Empty.", "", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_SearchASActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> PList;
    private javax.swing.JButton SearchAS;
    private javax.swing.JButton addButton;
    private javax.swing.JTextField admissionNo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> sessionList;
    private javax.swing.JLabel stClass;
    private javax.swing.JLabel stRoll;
    private javax.swing.JLabel stSec;
    private javax.swing.JLabel stSession;
    // End of variables declaration//GEN-END:variables

    @SuppressWarnings("unchecked")
    private void setData() {
        System.out.println("Mehod Called");
        try{
            ses =  tdi.selectSession();
            DefaultComboBoxModel dcm = new DefaultComboBoxModel<>();
            this.sessionList.setModel(dcm);
            for (Session ses1 : ses) {
                System.out.println(ses1.getName());
                dcm.addElement(ses1.getName());
            }    
        }catch(Exception ex){
            System.out.print(ex);
        }
    }
}
