/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DataType.Expence;

import com.sun.glass.events.KeyEvent;
import java.awt.Dimension;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import setting.ComboBoxFiter;

/**
 *
 * @author kumar
 */
public class ExpenceIFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form ExpenceIFrame
     */
    
    public ExpenceIFrame() {
        initComponents();
    }

    public ExpenceIFrame(Dimension size) {
        initComponents();
        setBounds(0,0,size.width-10, size.height-10);
      setVisible(true);
       DateFormat df = new SimpleDateFormat("d MMM, yyyy");
      this.jdate.setDate(new Date());
      clearField();
      selectData();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        etable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        jdate = new com.toedter.calendar.JDateChooser();
        jScrollPane3 = new javax.swing.JScrollPane();
        remark = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        title = new javax.swing.JComboBox<>();
        expence = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));
        jPanel1.setLayout(null);

        etable.setAutoCreateRowSorter(true);
        etable.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        etable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title", "Price", "Date", "Remarks"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(etable);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(10, 11, 670, 514);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Title :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(730, 80, 33, 17);

        price.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        price.setText("jTextField1");
        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });
        price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                priceKeyTyped(evt);
            }
        });
        jPanel1.add(price);
        price.setBounds(780, 123, 210, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Amount :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(710, 130, 70, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Remark :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(720, 200, 60, 17);

        save.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel1.add(save);
        save.setBounds(790, 310, 140, 30);

        jdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jdate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jdateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jdateFocusLost(evt);
            }
        });
        jdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jdateMouseExited(evt);
            }
        });
        jPanel1.add(jdate);
        jdate.setBounds(780, 30, 220, 30);

        remark.setColumns(20);
        remark.setLineWrap(true);
        remark.setRows(5);
        remark.setWrapStyleWord(true);
        remark.setName(""); // NOI18N
        remark.setNextFocusableComponent(save);
        remark.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                remarkKeyTyped(evt);
            }
        });
        jScrollPane3.setViewportView(remark);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(780, 160, 290, 130);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Date :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(730, 40, 40, 17);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(940, 310, 110, 30);

        title.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        title.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Title", "Tour", "Oil", "Supply", "Office", "Staff Payment", "School Management", "Other" }));
        title.setNextFocusableComponent(price);
        jPanel1.add(title);
        title.setBounds(780, 80, 280, 23);

        expence.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        expence.setText("------");
        jPanel1.add(expence);
        expence.setBounds(830, 390, 110, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Today Expence :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(710, 390, 110, 17);

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
            if(this.price.getText().length() == 0){
               JOptionPane.showMessageDialog(this,"Please Enter Price");
               return;
            }
            
            Expence expence = new Expence();
            expence.setTitle(this.title.getItemAt(title.getSelectedIndex()));
            expence.setRemark(this.remark.getText());
            expence.setPrice(Integer.parseInt(this.price.getText()));
            expence.setDate(jdate.getDate());

             System.out.printf("Submit click");
          int i = new ExpenceDaoImpl().insertExpence(expence);
            if(i!=0){
               System.out.print(" Data Save ");
               JOptionPane.showMessageDialog(this," Data Save ");
               clearField();
               selectData();

            }
            else{
                System.out.print(" Error during save ");
                JOptionPane.showMessageDialog(this,"Error during save Retry..");
            }
       
    }//GEN-LAST:event_saveActionPerformed

    private void jdateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jdateFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jdateFocusGained

    private void jdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jdateMouseExited
         
         selectData();
    }//GEN-LAST:event_jdateMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       selectData();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed

    private void priceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_priceKeyTyped
        ComboBoxFiter.numberValidation(evt);
        if(evt.getKeyChar() == KeyEvent.VK_ENTER){
            this.save.doClick();
        }
    }//GEN-LAST:event_priceKeyTyped

    private void jdateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jdateFocusLost
         selectData();
    }//GEN-LAST:event_jdateFocusLost

    private void remarkKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_remarkKeyTyped
         if(evt.getKeyChar() == KeyEvent.VK_ENTER){
            this.save.doClick();
        }
    }//GEN-LAST:event_remarkKeyTyped
    
    //clear field
    private void clearField(){
        this.remark.setText("");
        this.price.setText("0");
        this.title.setSelectedIndex(0);
    }
    
    // Select Value
    private void selectData(){
        int totalExpence = 0;
             Expence expence = new Expence();
            expence.setTitle(this.title.getItemAt(this.title.getSelectedIndex()));
            expence.setRemark(this.remark.getText());
            expence.setPrice(Integer.parseInt(this.price.getText()));
            expence.setDate(jdate.getDate());

         ExpenceDaoImpl cls =new ExpenceDaoImpl();
        Expence[] expenceListVector = null;
        expenceListVector = cls.selectExpence(expence);
        
        if(expenceListVector==null) {
            System.out.printf("Null");
        }
        
          DefaultTableModel modeal =(DefaultTableModel) this.etable.getModel(); 
          while(modeal.getRowCount()>0)
              modeal.removeRow(0);
               try{System.out.printf(expenceListVector[0].getTitle());
                    for(int i = 0;expenceListVector.length>i;i++){
                         
        modeal.addRow(new Object[]{expenceListVector[i].getTitle(),expenceListVector[i].getPrice(),expenceListVector[i].getDate(),expenceListVector[i].getRemark()});
                    totalExpence += expenceListVector[i].getPrice();                         
                    }
           }
        catch(Exception ex){
            //  Logger.getLogger(ClassesDaoImpl.class.getName()).log(Level.SEVERE, null, ex);
              
            System.out.print(ex);
        }
          this.expence.setText(" "+totalExpence);
       // this.classList.setListData(str);
     
        this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable etable;
    private javax.swing.JLabel expence;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private com.toedter.calendar.JDateChooser jdate;
    private javax.swing.JTextField price;
    private javax.swing.JTextArea remark;
    private javax.swing.JButton save;
    private javax.swing.JComboBox<String> title;
    // End of variables declaration//GEN-END:variables
}
