/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DataType.Expence;

import java.awt.Dimension;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kumar
 */
public class ExpenceIFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form ExpenceIFrame
     */
    public ExpenceIFrame() {
        initComponents();
    }

    public ExpenceIFrame(Dimension size) {
        initComponents();
        setBounds(0,0,size.width-10, size.height-10);
      setVisible(true);
       DateFormat df = new SimpleDateFormat("d MMM, yyyy");
      this.jdate.setDate(new Date());
      clearField();
      selectData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        etable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        title = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        jdate = new com.toedter.calendar.JDateChooser();
        jScrollPane3 = new javax.swing.JScrollPane();
        remark = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));
        jPanel1.setLayout(null);

        etable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title", "Price", "Date", "Remarks"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(etable);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(10, 11, 670, 514);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Title :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(720, 90, 33, 17);

        price.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        price.setText("jTextField1");
        jPanel1.add(price);
        price.setBounds(760, 130, 280, 23);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Price :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(710, 130, 50, 17);

        title.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        title.setText("jTextField1");
        jPanel1.add(title);
        title.setBounds(760, 90, 280, 23);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Remark :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(700, 160, 60, 17);

        save.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel1.add(save);
        save.setBounds(790, 310, 140, 30);

        jdate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jdateFocusGained(evt);
            }
        });
        jdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jdateMouseExited(evt);
            }
        });
        jPanel1.add(jdate);
        jdate.setBounds(790, 30, 220, 30);

        remark.setColumns(20);
        remark.setRows(5);
        jScrollPane3.setViewportView(remark);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(760, 160, 270, 120);

        jLabel4.setText("Date :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(730, 40, 40, 14);

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(940, 310, 110, 30);

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
            Expence expence = new Expence();
            expence.setTitle(this.title.getText());
            expence.setRemark(this.remark.getText());
            expence.setPrice(Integer.parseInt(this.price.getText()));
            expence.setDate(jdate.getDate());

             System.out.printf("Submit click");
          int i = new ExpenceDaoImpl().insertExpence(expence);
            if(i!=0){
                System.out.print("Data inserted Employ ID :"+i);
                JOptionPane.showMessageDialog(this,"Data Save...Employ ID :"+i);
               clearField();
               selectData();

            }
            else{
                System.out.print("error during save");
                JOptionPane.showMessageDialog(this,"Error during save Retry..");
            }
       
    }//GEN-LAST:event_saveActionPerformed

    private void jdateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jdateFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jdateFocusGained

    private void jdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jdateMouseExited
         // TODO add your handling code here:
         selectData();
    }//GEN-LAST:event_jdateMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       selectData();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    //clear field
    private void clearField(){
        this.remark.setText("");
        this.price.setText("0");
        this.title.setText("");
    }
    
    // Select Value
    private void selectData(){
             Expence expence = new Expence();
            expence.setTitle(this.title.getText());
            expence.setRemark(this.remark.getText());
            expence.setPrice(Integer.parseInt(this.price.getText()));
            expence.setDate(jdate.getDate());

         ExpenceDaoImpl cls =new ExpenceDaoImpl();
        Expence[] expenceListVector = null;
        expenceListVector = cls.selectExpence(expence);
        
        if(expenceListVector==null) {
            System.out.printf("Null");
        }
        
          DefaultTableModel modeal =(DefaultTableModel) this.etable.getModel(); 
          while(modeal.getRowCount()>0)
              modeal.removeRow(0);
               try{System.out.printf(expenceListVector[0].getTitle());
                    for(int i = 0;expenceListVector.length>i;i++){
                         
                         modeal.addRow(new Object[]{expenceListVector[i].getTitle(),expenceListVector[i].getPrice(),expenceListVector[i].getDate(),expenceListVector[i].getRemark()});
                        
                       
                    }
           }
        catch(Exception ex){
            //  Logger.getLogger(ClassesDaoImpl.class.getName()).log(Level.SEVERE, null, ex);
              
            System.out.print(ex);
        }
       // this.classList.setListData(str);
     
        this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable etable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private com.toedter.calendar.JDateChooser jdate;
    private javax.swing.JTextField price;
    private javax.swing.JTextArea remark;
    private javax.swing.JButton save;
    private javax.swing.JTextField title;
    // End of variables declaration//GEN-END:variables
}
