/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package product;

import java.awt.Dimension;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author kumar
 */
public class ProductAdd extends javax.swing.JInternalFrame {
   
    private Product prd = new Product();
    private ProductDaoImpl pdi = new ProductDaoImpl();
    Product[] data;
    /**
     * Creates new form StudentAdmissionStage2
     */
    public ProductAdd() {
        initComponents();
        setData();
    }
    
     public ProductAdd(Dimension size) {
        initComponents();
        this.setData();
        setBounds(0,0,size.width-10, size.height-10);
      setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        PList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        pname = new javax.swing.JTextField();
        UpdateButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 255, 102));
        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setAutoscrolls(true);
        getContentPane().setLayout(null);

        PList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                PListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(PList);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(80, 70, 230, 380);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Product :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(350, 110, 60, 30);

        pname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(pname);
        pname.setBounds(430, 110, 150, 30);

        UpdateButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(UpdateButton);
        UpdateButton.setBounds(350, 270, 100, 25);

        addButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addButton);
        addButton.setBounds(490, 270, 110, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_PListValueChanged
        String pname1 = PList.getSelectedValue();
        pname.setText(pname1);
    }//GEN-LAST:event_PListValueChanged

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
             String value = pname.getText();
             prd.setName(value);
             System.out.print(value);
             if(value != ""){
                int i = pdi.InsetProduct(prd);
                if(i != 0){
                   JOptionPane.showMessageDialog(null, "Added Successfully", "", JOptionPane.INFORMATION_MESSAGE);
                   pname.setText("");
                   this.setData();
                }
                else{
                    JOptionPane.showMessageDialog(null, "Something went wrong", "", JOptionPane.INFORMATION_MESSAGE);
                }
             }
             else{
                 JOptionPane.showMessageDialog(null, "Input Box is Empty.", "", JOptionPane.INFORMATION_MESSAGE);
                 pname.setFocusable(true);
             }
             
             //dlm.addElement(value); 
    }//GEN-LAST:event_addButtonActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
             String value = pname.getText();
             int ind = PList.getSelectedIndex();
             System.out.println(data[ind].getId());
             System.out.println(data[ind].getName());
             data[ind].setName(value);
             
             //System.out.println(value);
            // System.out.println(ind);
             if(value != ""){
                int i = pdi.updateProduct(data[ind]);
                if(i != 0){
                   JOptionPane.showMessageDialog(null, "Updated Successfully", "", JOptionPane.INFORMATION_MESSAGE);
                   pname.setText("");
                   this.setData();
                }
                else{
                    JOptionPane.showMessageDialog(null, "Something went wrong", "", JOptionPane.INFORMATION_MESSAGE);
                }
             }
             else{
                 JOptionPane.showMessageDialog(null, "Input Box is Empty.", "", JOptionPane.INFORMATION_MESSAGE);
                 pname.setFocusable(true);
             }
    }//GEN-LAST:event_UpdateButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> PList;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JButton addButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pname;
    // End of variables declaration//GEN-END:variables

    @SuppressWarnings("unchecked")
    private void setData() {
        System.out.println("Mehod Called");
        data = pdi.getProduct();
        DefaultListModel<String> model = new DefaultListModel<>();
        this.PList.setModel(model);
        try{
            for (Product data1 : data) {
                System.out.println(data1.getName());
                model.addElement(data1.getName());
            }    
        }catch(Exception ex){
            System.out.print(ex);
        }
    }
}
